### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by ceteri** [NYU-CI/RCPublications#23]
The JSON formatting is a bit jumbled and throwing exceptions in `publications/partitions/20191119_SurveyofIncomeandProgramParticipation_publications.json`

> json.decoder.JSONDecodeError: Expecting ',' delimiter: line 86 column 1 (char 3004)

**Comment by srand525** [comment]
file should be fine now
```python test.py partitions/20191119_SurveyofIncomeandProgramParticipation_publications.json
['partitions/20191119_SurveyofIncomeandProgramParticipation_publications.json']
.
20 publications loaded
...
----------------------------------------------------------------------
Ran 4 tests in 0.002s

OK

```

**Comment by ceteri** [comment]
Is that committed to `master` branch also?

When I checkout `master` and run unit tests now, I get these errors:
```
======================================================================
ERROR: test_each_field (__main__.TestVerifyPublications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 41, in setUp
    self.publications.extend(json.load(f))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 86 column 1 (char 3004)

======================================================================
ERROR: test_file_loaded (__main__.TestVerifyPublications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 41, in setUp
    self.publications.extend(json.load(f))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 86 column 1 (char 3004)

======================================================================
ERROR: test_has_required_fields (__main__.TestVerifyPublications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 41, in setUp
    self.publications.extend(json.load(f))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 86 column 1 (char 3004)

======================================================================
ERROR: test_has_valid_url (__main__.TestVerifyPublications)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test.py", line 41, in setUp
    self.publications.extend(json.load(f))
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 86 column 1 (char 3004)

----------------------------------------------------------------------
Ran 4 tests in 0.005s

FAILED (errors=4)
```

**Comment by srand525** [comment]
it is now - apologies

**Comment by ceteri** [comment]
Looks good, thanks!
